---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: core
description: Custom Bazzite-Nvidia-Open based OS image for development, AI, and gaming

base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: stable

modules:
  - from-file: packages-rpm.yml
  - from-file: packages-flatpak.yml
  - from-file: fonts.yml
  - from-file: system-config.yml
  - type: signing
